---
- name: terminate instance
  amazon.aws.ec2_instance:
    profile: "{{ aws_profile }}"
    region: "{{ aws_region }}"
    instance_ids: "{{ instance }}"
    state: absent
    wait: yes
  ignore_errors: yes

- name: wait until instance terminated
  amazon.aws.ec2_instance_info:
    instance_ids:
      - "{{ instance }}"
  register: result_instance_status
  retries: 30
  delay: 10
  until: result_instance_status.instances[0].state.name == "terminated"

# Security group is for common use already, don't need delete it everytime

- name: remove guest_ip from inventory file
  community.general.ini_file:
    path: "{{ playbook_dir }}/inventory"
    section: cloud:vars
    option: guest_ip
    state: absent
  ignore_errors: yes

- name: remove instance_id from inventory file
  community.general.ini_file:
    path: "{{ playbook_dir }}/inventory"
    section: cloud:vars
    option: instance
    state: absent
  ignore_errors: yes
