- name: "delete resource group {{ resource_group_name }}"
  azure_rm_resourcegroup:
    name: "{{ resource_group_name }}"
    auth_source: env
    location: eastus
    force_delete_nonempty: yes
    state: absent
  ignore_errors: yes
