---
- name: remove openstack instance
  openstack.cloud.server:
    cloud: rhos-01
    name: "{{ instance }}"
    state: absent
  ignore_errors: yes

- name: remove guest_ip from inventory file
  community.general.ini_file:
    path: "{{ playbook_dir }}/inventory"
    section: cloud:vars
    option: guest_ip
    state: absent
  ignore_errors: yes

- name: remove uuid from inventory file
  community.general.ini_file:
    path: "{{ playbook_dir }}/inventory"
    section: cloud:vars
    option: instance
    state: absent
  ignore_errors: yes
