---
- name: random number as part of instance name
  set_fact:
    random_number: "{{ 99 | random(start=11) }}"

- name: create openstack configuration folder
  file:
    path: ~/.config/openstack
    state: directory

- name: set vault password file
  copy:
    content: "{{ lookup('env', 'VAULT_PASSWORD') }}"
    dest: "~/.config/ansible-vault"

- name: save clouds.yaml to ~/.config/openstack
  command: ansible-vault decrypt -v --vault-password-file ~/.config/ansible-vault {{ role_path }}/files/clouds-yaml --output ~/.config/openstack/clouds.yaml

- name: remove old openstack keypair
  os_keypair:
    cloud: psi-openstack
    state: absent
    name: kite-image-key

- name: create a new openstack keypair
  os_keypair:
    cloud: psi-openstack
    state: present
    name: kite-image-key
    public_key_file: "{{ playbook_dir }}/key/identity.pub"

- name: create security group
  os_security_group:
    cloud: psi-openstack
    name: kite-image
    state: present
    description: security group for kite image build server

- name: set ssh rule for security group kite
  os_security_group_rule:
    cloud: psi-openstack
    security_group: kite-image
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0

- name: set openstack instance name
  set_fact:
    instance_name: "kite-image-builder-{{ os }}-{{ random_number }}"

- name: deploy instance
  os_server:
    cloud: psi-openstack
    name: "{{ instance_name }}"
    image: "{{ images['fedora-33'] }}"
    flavor: "{{ flavor }}"
    network: "{{ network }}"
    key_name: kite-image-key
    security_groups: kite-image
    auto_ip: yes
    wait: yes
    timeout: 600
    userdata: |
      #!/bin/bash
      dnf -y install python3-dnf python3
  register: instance_result

- name: waits until instance is reachable
  wait_for:
    host: "{{ instance_result.openstack.public_v4 }}"
    port: 22
    search_regex: OpenSSH
    delay: 10

- name: add os instance ip into host group builder
  add_host:
    name: "{{ instance_result.openstack.public_v4 }}"
    groups: builder

- name: keep private key permission to 600
  file:
    path: "{{ playbook_dir }}/key/identity"
    mode: "0600"
