---
- name: delete old kite image first
  os_image:
    cloud: psi-openstack
    name: kite-openstack-{{ os }}
    state: absent

- name: upload image to psi openstack
  os_image:
    cloud: psi-openstack
    name: kite-openstack-{{ os }}
    filename: "{{ playbook_dir }}/{{ os }}.{{ image_type[cloud_platform] }}"
    # https://docs.openstack.org/glance/latest/admin/useful-image-properties.html
    properties:
      architecture: x86_64
      os_distro: rhel
      hw_rng_model: virtio
