---
name: RHEL 8.3 ESXi-7.0 image

on:
  schedule:
    # At 4:05 every Wed
    - cron: '5 4 * * 4'

jobs:
  esxi7_bios:
    name: build rhel 8.3 esxi 7.0 bios image
    runs-on: kite-runner

    steps:
      - name: Checkout kite-deploy repository
        uses: actions/checkout@v2

      - name: Build image
        run: ansible-playbook -v -i inventory -e esxi_firmware=bios -e cloud_platform=esxi build.yaml

      - name: Remove runner
        if: ${{ always() }}
        run: |
          RUNNER_NAME=$(cat /etc/hostname)
          curl -X PUT $KITE_CONTROLLER_API_NETLOC/runner/delete/$RUNNER_NAME > /dev/null 2>&1 &

  esxi7_efi:
    name: build rhel 8.3 esxi 7.0 efi image
    runs-on: kite-runner

    steps:
      - name: Checkout kite-deploy repository
        uses: actions/checkout@v2

      - name: Build image
        run: ansible-playbook -v -i inventory -e esxi_firmware=efi -e cloud_platform=esxi build.yaml

      - name: Remove runner
        if: ${{ always() }}
        run: |
          RUNNER_NAME=$(cat /etc/hostname)
          curl -X PUT $KITE_CONTROLLER_API_NETLOC/runner/delete/$RUNNER_NAME > /dev/null 2>&1 &
